# Generated by Django 4.0.2 on 2022-03-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('profile_image_url', models.ImageField(max_length=200, null=True, upload_to='')),
                ('description', models.TextField(null=True)),
                ('kakao_id', models.IntegerField()),
                ('email', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
